--- #YAML:1.0
name:                Catalyst-Plugin-Session-Store-DOD
version:             0.01
abstract:            ~
license:             ~
author:              
    - David Recordon <david@sixapart.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Catalyst::Plugin::Session:     0.05
    Catalyst::Runtime:             5.49
    Data::ObjectDriver:            0.40
    MIME::Base64:                  Storable
    Test::More:                    NEXT
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
